Upgrade `ecto_sql` dependency version
With upgrading the used `elixir` version, the `ecto` version used was
causing compilation issues. Specifically the error being seen was
```
==> ecto
Compiling 56 files (.ex)

== Compilation error in file lib/ecto/query.ex ==
** (Kernel.TypespecError) lib/ecto/query.ex:431: type dynamic/0 is a built-in type and it cannot be redefined
    (elixir 1.16.0) lib/kernel/typespec.ex:971: Kernel.Typespec.compile_error/2
    (stdlib 5.2) lists.erl:1599: :lists.foldl_1/3
    (elixir 1.16.0) lib/kernel/typespec.ex:226: Kernel.Typespec.translate_typespecs_for_module/2

```
The best course of action seemed to be upgrading `ecto_sql` to the
latest available.